### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [JalenPage/jalens-app9#1]
This is looking very good, apart from the indentation, which we may as well fix now, since we'll be building off this project in the future. The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have _every_ file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by JalenPage** [comment]
I have reconfigured my text editor so everything should be fine now.

**Comment by chrisvfritz** [comment]
Reconfiguring your text editor will make it easier to keep good indentation into the future, but you'll still have to manually update existing files where I'm still seeing hard-tabs. Those two videos should help with that if you'd like some tricks.

**Comment by JalenPage** [comment]
I have deleted all of the tabs in each of these files now.

**Comment by chrisvfritz** [comment]
:+1: Looks great!
